version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "devkitui"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo $API_URL
            - chmod 755 environment.sh
            - cat environment.sh
            - ./environment.sh
            - cat src/environments/environment.ts
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes